### ISSUE TITLE
Can't open launcher

### ISSUE THREAD

**Issue by Weihong1222** [Techarerm/BakeLauncher#5]
Traceback (most recent call last):
  File "main.py", line 7, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "LauncherBase.py", line 5, in <module>
ModuleNotFoundError: No module named 'ping3'
[PYI-10416:ERROR] Failed to execute script 'main' due to unhandled exception!

**Comment by Techarerm** [comment]
Fixed in version Dev-KA112524,

**Comment by Techarerm** [comment]
Fixed in version Dev-KA112524
